// backend/src/services/ai/registry/models/ai21.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Ai21 models registration
 * Auto-generated by add-models-to-registry.ts
 */
const ai21Models: ModelMetadata[] = [
  {
    modelId: 'ai21.jamba-1-5-large-v1:0',
    vendor: 'ai21',
    displayName: 'Jamba 1.5 Large',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'ai21.jamba-1-5-mini-v1:0',
    vendor: 'ai21',
    displayName: 'Jamba 1.5 Mini',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(ai21Models);

export { ai21Models };
