// backend/src/services/ai/registry/models/google.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Google models registration
 * Auto-generated by add-models-to-registry.ts
 */
const googleModels: ModelMetadata[] = [
  {
    modelId: 'google.gemma-3-12b-it',
    vendor: 'google',
    displayName: 'Gemma 3 12B IT',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'google.gemma-3-27b-it',
    vendor: 'google',
    displayName: 'Gemma 3 27B PT',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'google.gemma-3-4b-it',
    vendor: 'google',
    displayName: 'Gemma 3 4B IT',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(googleModels);

export { googleModels };
