// backend/src/services/ai/registry/models/meta.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Meta models registration
 * Auto-generated by add-models-to-registry.ts
 */
const metaModels: ModelMetadata[] = [
  {
    modelId: 'meta.llama3-70b-instruct-v1:0',
    vendor: 'meta',
    displayName: 'Llama 3 70B Instruct',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'meta.llama3-8b-instruct-v1:0',
    vendor: 'meta',
    displayName: 'Llama 3 8B Instruct',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(metaModels);

export { metaModels };
