// backend/src/services/ai/registry/models/minimax.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Minimax models registration
 * Auto-generated by add-models-to-registry.ts
 */
const minimaxModels: ModelMetadata[] = [
  {
    modelId: 'minimax.minimax-m2',
    vendor: 'minimax',
    displayName: 'MiniMax M2',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(minimaxModels);

export { minimaxModels };
