// backend/src/services/ai/registry/models/mistral.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Mistral models registration
 * Auto-generated by add-models-to-registry.ts
 */
const mistralModels: ModelMetadata[] = [
  {
    modelId: 'mistral.magistral-small-2509',
    vendor: 'mistral',
    displayName: 'Magistral Small 2509',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.ministral-3-14b-instruct',
    vendor: 'mistral',
    displayName: 'Ministral 14B 3.0',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.ministral-3-3b-instruct',
    vendor: 'mistral',
    displayName: 'Ministral 3B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.ministral-3-8b-instruct',
    vendor: 'mistral',
    displayName: 'Ministral 3 8B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.mistral-7b-instruct-v0:2',
    vendor: 'mistral',
    displayName: 'Mistral 7B Instruct',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.mistral-large-2402-v1:0',
    vendor: 'mistral',
    displayName: 'Mistral Large (24.02)',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: true,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.mistral-large-3-675b-instruct',
    vendor: 'mistral',
    displayName: 'Mistral Large 3',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: true,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.mistral-small-2402-v1:0',
    vendor: 'mistral',
    displayName: 'Mistral Small (24.02)',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.mixtral-8x7b-instruct-v0:1',
    vendor: 'mistral',
    displayName: 'Mixtral 8x7B Instruct',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.voxtral-mini-3b-2507',
    vendor: 'mistral',
    displayName: 'Voxtral Mini 3B 2507',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'mistral.voxtral-small-24b-2507',
    vendor: 'mistral',
    displayName: 'Voxtral Small 24B 2507',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(mistralModels);

export { mistralModels };
