// backend/src/services/ai/registry/models/moonshot.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Moonshot models registration
 * Auto-generated by add-models-to-registry.ts
 */
const moonshotModels: ModelMetadata[] = [
  {
    modelId: 'moonshot.kimi-k2-thinking',
    vendor: 'moonshot',
    displayName: 'Kimi K2 Thinking',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(moonshotModels);

export { moonshotModels };
