// backend/src/services/ai/registry/models/nvidia.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Nvidia models registration
 * Auto-generated by add-models-to-registry.ts
 */
const nvidiaModels: ModelMetadata[] = [
  {
    modelId: 'nvidia.nemotron-nano-12b-v2',
    vendor: 'nvidia',
    displayName: 'NVIDIA Nemotron Nano 12B v2 VL BF16',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'nvidia.nemotron-nano-3-30b',
    vendor: 'nvidia',
    displayName: 'Nemotron Nano 3 30B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'nvidia.nemotron-nano-9b-v2',
    vendor: 'nvidia',
    displayName: 'NVIDIA Nemotron Nano 9B v2',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(nvidiaModels);

export { nvidiaModels };
