// backend/src/services/ai/registry/models/openai.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Openai models registration
 * Auto-generated by add-models-to-registry.ts
 */
const openaiModels: ModelMetadata[] = [
  {
    modelId: 'openai.gpt-oss-120b-1:0',
    vendor: 'openai',
    displayName: 'gpt-oss-120b',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'openai.gpt-oss-20b-1:0',
    vendor: 'openai',
    displayName: 'gpt-oss-20b',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'openai.gpt-oss-safeguard-120b',
    vendor: 'openai',
    displayName: 'GPT OSS Safeguard 120B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'openai.gpt-oss-safeguard-20b',
    vendor: 'openai',
    displayName: 'GPT OSS Safeguard 20B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(openaiModels);

export { openaiModels };
