// backend/src/services/ai/registry/models/qwen.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Qwen models registration
 * Auto-generated by add-models-to-registry.ts
 */
const qwenModels: ModelMetadata[] = [
  {
    modelId: 'qwen.qwen3-32b-v1:0',
    vendor: 'qwen',
    displayName: 'Qwen3 32B (dense)',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'qwen.qwen3-coder-30b-a3b-v1:0',
    vendor: 'qwen',
    displayName: 'Qwen3-Coder-30B-A3B-Instruct',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'qwen.qwen3-next-80b-a3b',
    vendor: 'qwen',
    displayName: 'Qwen3 Next 80B A3B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

  {
    modelId: 'qwen.qwen3-vl-235b-a22b',
    vendor: 'qwen',
    displayName: 'Qwen3 VL 235B A22B',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: true,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(qwenModels);

export { qwenModels };
