// backend/src/services/ai/registry/models/twelvelabs.models.ts
// Standards: docs/STANDARDS.md

import { ModelRegistry, ModelMetadata } from '../model-registry';

/**
 * Twelvelabs models registration
 * Auto-generated by add-models-to-registry.ts
 */
const twelvelabsModels: ModelMetadata[] = [
  {
    modelId: 'twelvelabs.pegasus-1-2-v1:0',
    vendor: 'twelvelabs',
    displayName: 'Pegasus v1.2',
    description: 'Auto-generated model configuration',
    capabilities: {
      streaming: true,
      vision: false,
      functionCalling: false,
      maxContextWindow: 128000,
      maxOutputTokens: 4096,
    },
    supportedPlatforms: ['bedrock'],
    adapterClass: 'AmazonAdapter',
    recommendedParams: {
      temperature: 0.7,
      topP: 0.9,
      topK: 250,
      maxTokens: 2048,
    },
  },

];

// Auto-register all models
ModelRegistry.registerMany(twelvelabsModels);

export { twelvelabsModels };
